replicaCount: 1

image:
  repository: ghcr.io/failed33/cluster-bare-autoscaler/controller
  tag: "" # Defaults to the chart appVersion.
  pullPolicy: IfNotPresent

imagePullSecrets: []
priorityClassName: "system-cluster-critical"

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 32Mi

nodeSelector: {}
affinity: {}

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

serviceAccount:
  create: true
  name: cluster-bare-autoscaler

rbac:
  create: true

metricsDaemonset:
  enabled: true
  image:
    repository: ghcr.io/failed33/cluster-bare-autoscaler/metrics-exporter
    tag: "" # Defaults to the chart appVersion.
    pullPolicy: IfNotPresent
  port: 9100
  imagePullSecrets: []
  priorityClassName: "system-cluster-critical"
  resources:
    limits:
      memory: 32Mi
    requests:
      cpu: 8m
      memory: 20Mi
  tolerations: []
  nodeSelector: {}
  podLabels: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist

shutdownDaemonset:
  enabled: false
  port: 9101
  image:
    repository: ghcr.io/failed33/cluster-bare-autoscaler/poweroff-manager
    tag: "" # Defaults to the chart appVersion.
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  priorityClassName: "system-cluster-critical"
  resources:
    limits:
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 8Mi
  tolerations: []
  nodeSelector: {}
  podLabels: {}
  socketActivationPath: /run/cba-shutdown.sock

wolAgent:
  enabled: false
  nodeSelector: {}
  affinity: {}
  port: 9102
  image:
    repository:  ghcr.io/failed33/cluster-bare-autoscaler/wol-agent
    tag: "" # Defaults to the chart appVersion.
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  priorityClassName: "system-cluster-critical"
  resources:
    limits:
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 8Mi
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

config:
  logLevel: debug
  pollInterval: 10s
  cooldown: 5m
  bootCooldown: 60m
  shutdownMode: disabled
  powerOnMode: disabled
  minNodes: 0
  dryRun: true
  bootstrapCooldownSeconds: 10
  resourceBufferCPUPerc: 10
  resourceBufferMemoryPerc: 10
  nodeLabels:
    managed: cba.dev/is-managed
    disabled: cba.dev/disabled
  nodeAnnotations:
    mac: cba.dev/mac-address
  ignoreLabels:
    node-role.kubernetes.io/control-plane: ""
  loadAverageStrategy:
    enabled: true
    nodeThreshold: 0.2
    scaleDownThreshold: 0.5
    scaleUpThreshold: 0.75
    podLabel: "app=cluster-bare-autoscaler-sysmetrics"
    namespace: ""
    port: 9100
    timeoutSeconds: 3
    clusterEval: "p90" # p90 / average / median
